linters:
  enable:
    - golint
    - misspell
    - dupl
    - gocritic
    - prealloc
    - maligned
    - goconst
    - goimports
    - nakedret
    - scopelint
    - unconvert

issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - ((os\\.)?std(out|err)\\..*|.*\\.Close|.*\\.WriteString|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked
    # scopelint: the default go test table generation captures a range variable (tt), but it's ok
    - Using the variable on range scope `tt` in function literal