version: "3.2"

services:
  app:
    container_name: app
    build: ./
    volumes:
      - .:/app
      - go-cache:/go
    working_dir: /app
    environment:
      PORT: 80
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"
    command: go run main.go
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:11.1

volumes:
  go-cache:
